"""CLI的版本号"""
CLI_VER = '4.1.1'
RUNTIME_VER_1 = '0.1'
RUNTIME_VER_2 = '0.2'
RUNTIME_VER_3 = '0.3'
RUNTIME_VER_4 = '0.4'
"""最低可以支持客户端SDK（对应的DSL）的版本号"""
TARGET_RUNTIME_VER = RUNTIME_VER_3
FORCE_TARGET = None
