source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '8.0'

target 'DreamBox_iOS_Example' do
  pod 'DreamBox_iOS', :path => '../'
  pod 'DBDebugTool', :git => 'git@git.xiaojukeji.com:DreamBox/dbdebugtool_ios.git'
  pod 'LookinServer'

  target 'DreamBox_iOS_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
