# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'DBPlayGround_iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
	
  pod 'SocketRocket'
  pod 'DreamBox_iOS', :path => '../core-ios/'
end
